standalone_tags:
  [
  ]

tag_bundles:
  [
    {
      name: 'apriltag bundle'
      layout:
        [
          {id: 2, size: }
          {id: 4, size: }
          {id: 6, size: }
          {id: 8, size: }
        ]
    }
  ]
